-- MUESTRA LAS BASES EXISTENTES
SELECT name FROM sys.databases;
GO

-- USAR TABLA
USE RESERVACIONES;
GO

-- MUESTRA LAS TABLAS DE LA BASE ACTUAL
SELECT TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES;
GO

-- CONSULTAS
SELECT * FROM CLIENTE;
SELECT * FROM V_CLIENTE;
GO

SELECT * FROM PELICULA;
SELECT * FROM V_PELICULA;
GO

SELECT * FROM SALA;
SELECT * FROM V_SALA;
GO

SELECT * FROM ASIENTO;
SELECT * FROM V_ASIENTO;
GO

SELECT * FROM FUNCION;
SELECT * FROM RESERVACION;
SELECT * FROM V_RESERVACION;
GO

